version: 0.2

phases:
    pre_build:
        commands:
            - aws s3 rm s3://$BUCKET_NAME --recursive
    build:
        commands:
            - aws s3 cp . s3://$BUCKET_NAME --recursive --acl public-read
    post_build:
        commands:
            - echo Build successful
